[bot]
# Bot token
token = "YOUR_BOT_TOKEN"

# Bot owners
owners = [123456789]

# Required channel ID (with -100 prefix for private channels)
required_channel_id = -1002451767254

# Channel invite link
required_channel_invite = "https://t.me/+_lWXgZC_XNMwYWRi" 