name: Deploy to New Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}

    - name: Create target directory on server
      run: |
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "mkdir -p /home/root/telegramStarsBot"

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no -r * root@185.239.48.81:/home/root/telegramStarsBot

    - name: Set up virtual environment and install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"

    - name: Set up environment variables
      run: |
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && echo 'BOT_TOKEN=${{ secrets.BOT_TOKEN }}' > .env"
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && echo 'BOT_OWNERS=${{ secrets.BOT_OWNERS }}' >> .env"
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && echo 'BOT_REQUIRED_CHANNEL_ID=${{ secrets.BOT_REQUIRED_CHANNEL_ID }}' >> .env"
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && echo 'BOT_REQUIRED_CHANNEL_INVITE=${{ secrets.BOT_REQUIRED_CHANNEL_INVITE }}' >> .env"
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && echo 'BOT_OPENAI_API_KEY=${{ secrets.BOT_OPENAI_API_KEY }}' >> .env"
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && echo 'BOT_ASSISTANT_ID=${{ secrets.BOT_ASSISTANT_ID }}' >> .env"

    - name: Initialize database
      run: |
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "cd /home/root/telegramStarsBot && source venv/bin/activate && python3 -c 'from utils.db import create_db; import asyncio; asyncio.run(create_db())'"

    - name: Restart bot service
      run: |
        ssh -o StrictHostKeyChecking=no root@185.239.48.81 "sudo systemctl restart telegram_bot"
