# .github/workflows/deploy.yml
name: Deploy to Cloud.ru

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no -r . user@your_cloud.ru_server_ip:/home/user/telegramStarsBot

    - name: Install dependencies and create .env file
      run: |
        ssh -o StrictHostKeyChecking=no user@your_cloud.ru_server_ip << 'EOF'
          cd /home/user/telegramStarsBot
          sudo apt update && sudo apt install -y python3-pip
          pip3 install -r requirements.txt

          # Создание .env файла с использованием секретов GitHub
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          
          # Запустите приложение
          python3 main.py &
        EOF
