name: Deploy to Cloud.ru

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}

    - name: Create target directory on server
      run: |
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "mkdir -p /home/anashkin/telegramStarsBot"

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no -r * anashkin@45.155.205.196:/home/anashkin/telegramStarsBot

    - name: Set up virtual environment and install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"

    - name: Set up environment variables
      run: |
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && echo 'BOT_TOKEN=${{ secrets.BOT_TOKEN }}' > .env"
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && echo 'BOT_OWNERS=${{ secrets.BOT_OWNERS }}' >> .env"
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && echo 'BOT_REQUIRED_CHANNEL_ID=${{ secrets.BOT_REQUIRED_CHANNEL_ID }}' >> .env"
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && echo 'BOT_REQUIRED_CHANNEL_INVITE=${{ secrets.BOT_REQUIRED_CHANNEL_INVITE }}' >> .env"
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && echo 'BOT_OPENAI_API_KEY=${{ secrets.BOT_OPENAI_API_KEY }}' >> .env"
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "cd /home/anashkin/telegramStarsBot && echo 'BOT_ASSISTANT_ID=${{ secrets.BOT_ASSISTANT_ID }}' >> .env"

    - name: Restart bot service
      run: |
        ssh -o StrictHostKeyChecking=no anashkin@45.155.205.196 "sudo systemctl restart telegram_bot"
